#! /bin/bash

# DESCRIPTION

# SCRIPTDIR: Get the (relative) path to the script
# SCRIPTDIR="$(dirname "$0")"

apt-get -y install python3 python3-pip python3-dev
apt-get -y install libxcb-render0-dev libffi-dev libcairo2 libpangocairo-1.0.0
apt-get -y install python3-dbus python3-gobject

apt-get -y install pavucontrol pnmixer

pip3 install xcffib
pip3 install cairocffi
# asyncio is part of standard library in python >=3.4

pip3 install qtile

cp qtile-session /usr/local/bin/qtile-session
cp qtile.desktop /usr/share/xsessions/

# CODE
