#! /bin/bash

# Take data on stdin, open for user to edit in $EDITOR or $VISUAL,
# output edited data on stdout.

#
# Copyright 2014 Nicholas Martin Booker <NMBooker@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# SCRIPTDIR: Get the (relative) path to the script
# SCRIPTDIR="$(dirname $0)"

set -e

TMPF="$(tempfile)"
EDIT="$(if [ -z "$1" ] ; then
    if [ -z "$VISUAL" ] ; then
        echo $EDITOR
    else
        echo $VISUAL
    fi
else
    echo $1
fi
)"

cat > "$TMPF"

"$EDIT" "$TMPF" </dev/tty >/dev/tty

cat "$TMPF"

rm "$TMPF"
