#! /usr/bin/env python

"""Print the first filled-in argument on stdout.
"""

import sys
import argparse

def main(argv):
    """Main program."""
    nzArgs = filter(lambda x:x, argv[1:])
    if nzArgs:
        print(nzArgs[0])
    else:
        sys.stderr.write("No non-zero argument\n")
        sys.exit(3)
    return

if __name__ == "__main__":
    main(sys.argv)
