#! /usr/bin/env python3

"""Find unclean git repositories.

Design:

Read a list of git repositories and their usual remotes and branches from a file.

For each git repo, look for unpushed and unmerged commits in those branches,
and report them on STDOUT.
Also report on STDOUT if there are uncommitted changes.
Print nothing if there are no unused branches.

Provide a --fetch option to automatically do git fetch remote branch on
each repo first.
"""

import sys
import argparse

def main(options):
    """Main program."""
    # MAIN_LOGIC
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="DESCRIPTION",
    )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
