#! /usr/bin/env python

"""Convert YAML to JSON.
"""

import sys
import argparse

import yaml
try:
    # Use C implementation if available, for speed
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

import json

def main(options):
    """Main program."""
    json.dump(yaml.load(sys.stdin, Loader=Loader), sys.stdout)
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="YAML on stdin, JSON on stdout",
    )
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
