#! /usr/bin/env python

"""Convert YAML to JSON.
"""

import sys
import argparse

import yaml
try:
    # Use C implementation if available, for speed
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

import json

def main(options):
    """Main program."""
    json.dump(yaml.load(sys.stdin, Loader=Loader), sys.stdout)
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="YAML on stdin, JSON on stdout",
    )
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())


"""
Copyright (c) 2014 Nicholas Martin Booker <NMBooker@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
